name: CI/CD Pipeline

on:
  push:
    branches:
      - "main"
      - "develop"

permissions:
  id-token: write
  contents: read

jobs:
  update-manifests:
    runs-on: ubuntu-latest

    env:
      ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update Kubernetes manifests
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
          APP_NAME: "sample-app"
          INGRESS_HOST: ${{ secrets.INGRESS_HOST }}
        run: |
          # 매니페스트 저장소 클론
          git clone "https://$GIT_TOKEN@github.com/KimMunjin/SampleProject-manifest.git"
          cd SampleProject-manifest/$ENVIRONMENT
          
          # 모든 yaml 파일에서 플레이스홀더 치환
          for file in *.yaml; do
            sed -i "s|\${AWS_ACCOUNT_ID}|$AWS_ACCOUNT_ID|g" $file
            sed -i "s|\${AWS_REGION}|$AWS_REGION|g" $file
            sed -i "s|\${ECR_REPOSITORY}|$ECR_REPOSITORY|g" $file
            sed -i "s|\${IMAGE_TAG}|$IMAGE_TAG|g" $file
            sed -i "s|\${APP_NAME}|$APP_NAME|g" $file
            sed -i "s|\${INGRESS_HOST}|$INGRESS_HOST|g" $file
          done
          
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          
          # 변경 사항이 있는지 확인
          if [[ -n "$(git status --porcelain)" ]]; then
            git add .
            git commit -m "Update $ENVIRONMENT manifests for ${IMAGE_TAG}"
            git push "https://$GIT_TOKEN@github.com/KimMunjin/SampleProject-manifest.git" main
          fi